@Library("Shared") _

pipeline {
    agent any
    parameters {
        string(name: "DOCKER_IMAGE_TAG", defaultValue: "", description: "Docker Image Tag built by the CI")
    }
    stages {
        stage("Workspace Cleanup") {
            steps {
                cleanWs()
            }
        }
        stage("Cloning Code") {
            steps {
                script {
                    clone_with_cred("codilio", "main")
                }
            }
        }
        stage("Verify: Docker Image Tags") {
            steps {
                script {
                    echo "DOCKER_IMAGE_TAG: ${params.DOCKER_IMAGE_TAG}"
                }
            }
        }
        stage("Update: Kubernetes Manifests") {
            steps {
                dir("kubernetes") {
                    script {
                        sh """
                sed -i -e s/codilio-beta.*/codilio-beta:${params.DOCKER_IMAGE_TAG}/g codilio-deployment.yml
                        """
                    }
                }
            }
        }
        stage("Git: Code update and push to Github") {
            steps {
                script {
                    git_push("codilio", "main")
                }
            }
        }
    }
    post {
        success {
            script {
                emailext attachLog: true,
                from: 'pratyushpragyey@gmail.com',
                subject: "Codilio Application has been updated and deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'pratyushpragyey@gmail.com',
            mimeType: 'text/html'
            }
        }
      failure {
            script {
                emailext attachLog: true,
                from: 'pratyushpragyey@gmail.com',
                subject: "Codilio Application build failed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'pratyushpragyey@gmail.com',
            mimeType: 'text/html'
            }
        }
        
    }
}
